# Generated by Django 4.2.4 on 2023-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('product_description', models.TextField(verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='изображение')),
                ('product_category', models.CharField(max_length=30, verbose_name='категория')),
                ('product_purchase_price', models.IntegerField(verbose_name='цена')),
                ('product_date_of_create', models.DateField(verbose_name='дата создания')),
                ('product_last_modified_date', models.DateField(blank=True, null=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
